### ISSUE TITLE
feature: backup and restore

### ISSUE THREAD

**Issue by robinWongM** [VMatrixTeam/seaweedfs-operator#1]
```yaml
spec:
  image: chrislusf/seaweedfs:2.07
  backup:
    storages:
      sas:
        type: filesystem
        volume:
          persistentVolumeClaim:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 6Gi
    schedule:
      - name: "sat-night-backup"
        schedule: "0 0 * * 6"
        keep: 3
        storageName: sas
```

Reference:
1. https://www.percona.com/doc/kubernetes-operator-for-pxc/backups.html
